export const environment = {
  production: true,
  PROVIDER:'https://bsc-dataseed.binance.org/',
  CONTRACT_ADDRESS:'0x50acb087696ae5971b9e517aecebd829f76fbfc4',
  TOKENSALE_ADDRESS:'0x89f75c5d6c42ebe547844edb5860d081ff01c541',
  LOGO:'assets/images/logo.png',
  TITLE:'BigTime',
  NETWORK:'BSC',
  TYPE:'MAINNET',
  FROMTOKENNAME:'BNB',
  TOTOKENNAME:'BIG',
  TRANSLINK:'https://bscscan.com/tx',
  SUPPORTMAIL:'info@bigtime.co',
  FACEBOOK:'',
  INSTAGRAM:'',
  PINTEREST:'',
  TWITTER:'',
  GOOGLE:'',
  WHATSAPP:'',
  LINKEDIN:'',
};
